[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["net","os-poll","os-ext"] }
env_logger = "0.10.0"
log = "0.4.17"
arrayvec = "0.7.4"
byteorder = "1.4.3"
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }