#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u16)]
pub enum ResourceRecordType {
    A,
    NS,
    MD,
    MF,
    CNAME,
    SOA,
    MB,
    MG,
    MR,
    NULL,
    WKS,
    PTR,
    HINFO,
    MINFO,
    MX,
    TXT,
    RP,
    AFSDB,
    X25,
    ISDN,
    RT,
    NSAP,
    NSAP_PTR,
    SIG,
    KEY,
    PX,
    GPOS,
    AAAA,
    LOC,
    NXT,
    EID,
    NIMLOC,
    SRV,
    ATMA,
    NAPTR,
    KX,
    CERT,
    A6,
    DNAME,
    SINK,
    OPT,
    APL,
    DS,
    SSHFP,
    IPSECKEY,
    RRSIG,
    NSEC,
    DNSKEY,
    DHCID,
    NSEC3,
    NSEC3PARAM,
    TLSA,
    SMIMEA,
    HIP,
    NINFO,
    RKEY,
    TALINK,
    CDS,
    CDNSKEY,
    OPENPGPKEY,
    CSYNC,
    ZONEMD,
    SVCB,
    HTTPS,
    SPF,
    UINFO,
    UID,
    GID,
    UNSPEC,
    NID,
    L32,
    L64,
    LP,
    EUI48,
    EUI64,
    TKEY,
    TSIG,
    IXFR,
    AXFR,
    MAILB,
    MAILA,
    ANY,
    URI,
    CAA,
    AVC,
    DOA,
    AMTRELAY,
    TA,
    DLV,
}

impl ResourceRecordType {
    pub fn id(&self) -> u16 {
        match *self {
            ResourceRecordType::A => 1,
            ResourceRecordType::NS => 2,
            ResourceRecordType::MD => 3,
            ResourceRecordType::MF => 4,
            ResourceRecordType::CNAME => 5,
            ResourceRecordType::SOA => 6,
            ResourceRecordType::MB => 7,
            ResourceRecordType::MG => 8,
            ResourceRecordType::MR => 9,
            ResourceRecordType::NULL => 10,
            ResourceRecordType::WKS => 11,
            ResourceRecordType::PTR => 12,
            ResourceRecordType::HINFO => 13,
            ResourceRecordType::MINFO => 14,
            ResourceRecordType::MX => 15,
            ResourceRecordType::TXT => 16,
            ResourceRecordType::RP => 17,
            ResourceRecordType::AFSDB => 18,
            ResourceRecordType::X25 => 19,
            ResourceRecordType::ISDN => 20,
            ResourceRecordType::RT => 21,
            ResourceRecordType::NSAP => 22,
            ResourceRecordType::NSAP_PTR => 23,
            ResourceRecordType::SIG => 24,
            ResourceRecordType::KEY => 25,
            ResourceRecordType::PX => 26,
            ResourceRecordType::GPOS => 27,
            ResourceRecordType::AAAA => 28,
            ResourceRecordType::LOC => 29,
            ResourceRecordType::NXT => 30,
            ResourceRecordType::EID => 31,
            ResourceRecordType::NIMLOC => 32,
            ResourceRecordType::SRV => 33,
            ResourceRecordType::ATMA => 34,
            ResourceRecordType::NAPTR => 35,
            ResourceRecordType::KX => 36,
            ResourceRecordType::CERT => 37,
            ResourceRecordType::A6 => 38,
            ResourceRecordType::DNAME => 39,
            ResourceRecordType::SINK => 40,
            ResourceRecordType::OPT => 41,
            ResourceRecordType::APL => 42,
            ResourceRecordType::DS => 43,
            ResourceRecordType::SSHFP => 44,
            ResourceRecordType::IPSECKEY => 45,
            ResourceRecordType::RRSIG => 46,
            ResourceRecordType::NSEC => 47,
            ResourceRecordType::DNSKEY => 48,
            ResourceRecordType::DHCID => 49,
            ResourceRecordType::NSEC3 => 50,
            ResourceRecordType::NSEC3PARAM => 51,
            ResourceRecordType::TLSA => 52,
            ResourceRecordType::SMIMEA => 53,
            ResourceRecordType::HIP => 55,
            ResourceRecordType::NINFO => 56,
            ResourceRecordType::RKEY => 57,
            ResourceRecordType::TALINK => 58,
            ResourceRecordType::CDS => 59,
            ResourceRecordType::CDNSKEY => 60,
            ResourceRecordType::OPENPGPKEY => 61,
            ResourceRecordType::CSYNC => 62,
            ResourceRecordType::ZONEMD => 63,
            ResourceRecordType::SVCB => 64,
            ResourceRecordType::HTTPS => 65,
            ResourceRecordType::SPF => 99,
            ResourceRecordType::UINFO => 100,
            ResourceRecordType::UID => 101,
            ResourceRecordType::GID => 102,
            ResourceRecordType::UNSPEC => 103,
            ResourceRecordType::NID => 104,
            ResourceRecordType::L32 => 105,
            ResourceRecordType::L64 => 106,
            ResourceRecordType::LP => 107,
            ResourceRecordType::EUI48 => 108,
            ResourceRecordType::EUI64 => 109,
            ResourceRecordType::TKEY => 249,
            ResourceRecordType::TSIG => 250,
            ResourceRecordType::IXFR => 251,
            ResourceRecordType::AXFR => 252,
            ResourceRecordType::MAILB => 253,
            ResourceRecordType::MAILA => 254,
            ResourceRecordType::ANY => 255,
            ResourceRecordType::URI => 256,
            ResourceRecordType::CAA => 257,
            ResourceRecordType::AVC => 258,
            ResourceRecordType::DOA => 259,
            ResourceRecordType::AMTRELAY => 260,
            ResourceRecordType::TA => 32768,
            ResourceRecordType::DLV => 32769,
        }
    }

    pub fn try_from_id(id: u16) -> Option<Self> {
        match id {
            1 => Some(ResourceRecordType::A),
            2 => Some(ResourceRecordType::NS),
            3 => Some(ResourceRecordType::MD),
            4 => Some(ResourceRecordType::MF),
            5 => Some(ResourceRecordType::CNAME),
            6 => Some(ResourceRecordType::SOA),
            7 => Some(ResourceRecordType::MB),
            8 => Some(ResourceRecordType::MG),
            9 => Some(ResourceRecordType::MR),
            10 => Some(ResourceRecordType::NULL),
            11 => Some(ResourceRecordType::WKS),
            12 => Some(ResourceRecordType::PTR),
            13 => Some(ResourceRecordType::HINFO),
            14 => Some(ResourceRecordType::MINFO),
            15 => Some(ResourceRecordType::MX),
            16 => Some(ResourceRecordType::TXT),
            17 => Some(ResourceRecordType::RP),
            18 => Some(ResourceRecordType::AFSDB),
            19 => Some(ResourceRecordType::X25),
            20 => Some(ResourceRecordType::ISDN),
            21 => Some(ResourceRecordType::RT),
            22 => Some(ResourceRecordType::NSAP),
            23 => Some(ResourceRecordType::NSAP_PTR),
            24 => Some(ResourceRecordType::SIG),
            25 => Some(ResourceRecordType::KEY),
            26 => Some(ResourceRecordType::PX),
            27 => Some(ResourceRecordType::GPOS),
            28 => Some(ResourceRecordType::AAAA),
            29 => Some(ResourceRecordType::LOC),
            30 => Some(ResourceRecordType::NXT),
            31 => Some(ResourceRecordType::EID),
            32 => Some(ResourceRecordType::NIMLOC),
            33 => Some(ResourceRecordType::SRV),
            34 => Some(ResourceRecordType::ATMA),
            35 => Some(ResourceRecordType::NAPTR),
            36 => Some(ResourceRecordType::KX),
            37 => Some(ResourceRecordType::CERT),
            38 => Some(ResourceRecordType::A6),
            39 => Some(ResourceRecordType::DNAME),
            40 => Some(ResourceRecordType::SINK),
            41 => Some(ResourceRecordType::OPT),
            42 => Some(ResourceRecordType::APL),
            43 => Some(ResourceRecordType::DS),
            44 => Some(ResourceRecordType::SSHFP),
            45 => Some(ResourceRecordType::IPSECKEY),
            46 => Some(ResourceRecordType::RRSIG),
            47 => Some(ResourceRecordType::NSEC),
            48 => Some(ResourceRecordType::DNSKEY),
            49 => Some(ResourceRecordType::DHCID),
            50 => Some(ResourceRecordType::NSEC3),
            51 => Some(ResourceRecordType::NSEC3PARAM),
            52 => Some(ResourceRecordType::TLSA),
            53 => Some(ResourceRecordType::SMIMEA),
            55 => Some(ResourceRecordType::HIP),
            56 => Some(ResourceRecordType::NINFO),
            57 => Some(ResourceRecordType::RKEY),
            58 => Some(ResourceRecordType::TALINK),
            59 => Some(ResourceRecordType::CDS),
            60 => Some(ResourceRecordType::CDNSKEY),
            61 => Some(ResourceRecordType::OPENPGPKEY),
            62 => Some(ResourceRecordType::CSYNC),
            99 => Some(ResourceRecordType::SPF),
            100 => Some(ResourceRecordType::UINFO),
            101 => Some(ResourceRecordType::UID),
            102 => Some(ResourceRecordType::GID),
            103 => Some(ResourceRecordType::UNSPEC),
            104 => Some(ResourceRecordType::NID),
            105 => Some(ResourceRecordType::L32),
            106 => Some(ResourceRecordType::L64),
            107 => Some(ResourceRecordType::LP),
            108 => Some(ResourceRecordType::EUI48),
            109 => Some(ResourceRecordType::EUI64),
            249 => Some(ResourceRecordType::TKEY),
            250 => Some(ResourceRecordType::TSIG),
            251 => Some(ResourceRecordType::IXFR),
            252 => Some(ResourceRecordType::AXFR),
            253 => Some(ResourceRecordType::MAILB),
            254 => Some(ResourceRecordType::MAILA),
            255 => Some(ResourceRecordType::ANY),
            256 => Some(ResourceRecordType::URI),
            257 => Some(ResourceRecordType::CAA),
            258 => Some(ResourceRecordType::AVC),
            259 => Some(ResourceRecordType::DOA),
            260 => Some(ResourceRecordType::AMTRELAY),
            32768 => Some(ResourceRecordType::TA),
            32769 => Some(ResourceRecordType::DLV),
            _ => None,
        }
    }
}
